export const CLASSES = [
  {
    id: 'fighter',
    name: 'Fighter',
    emoji: '⚔️',
    tagline: 'Masters of combat. Unmatched in sustained battle.',
    description: 'Fighters are the backbone of any adventuring party — trained warriors who have mastered weapons and armor. They are tough, reliable, and capable of incredible bursts of combat power.',
    hitDie: 10,
    primaryStat: 'STR',
    armorProficiencies: ['Light', 'Medium', 'Heavy', 'Shields'],
    weaponProficiencies: ['Simple', 'Martial'],
    savingThrows: ['STR', 'CON'],
    skillChoices: { count: 2, options: ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation', 'Perception', 'Survival'] },
    startingEquipment: ['Chain mail', 'Longsword', 'Shield', 'Two handaxes', "Explorer's pack"],
    level1Abilities: [
      { name: 'Second Wind', description: 'As a bonus action, regain 1d10 + Fighter level HP. Once per short rest.' },
      { name: 'Fighting Style', description: 'Choose a fighting style: Defense (+1 AC in armor), Dueling (+2 damage with one-handed weapon), or Great Weapon Fighting (reroll 1s and 2s on damage with two-handed weapons).' },
    ],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    emoji: '🔮',
    tagline: 'Masters of arcane magic. Knowledge is power.',
    description: 'Wizards are scholars of magic who command the most powerful spells in existence. Fragile in body but devastating in potential, they turn the fabric of reality to their will through years of intense study.',
    hitDie: 6,
    primaryStat: 'INT',
    armorProficiencies: [],
    weaponProficiencies: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light crossbows'],
    savingThrows: ['INT', 'WIS'],
    skillChoices: { count: 2, options: ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'] },
    startingEquipment: ['Spellbook', 'Arcane focus', 'Dagger', "Scholar's pack"],
    level1Abilities: [
      { name: 'Spellcasting', description: 'You can cast wizard spells using INT as your spellcasting ability. Spell save DC = 8 + proficiency + INT modifier.' },
      { name: 'Arcane Recovery', description: 'Once per day during a short rest, recover spell slots totaling up to half your wizard level (rounded up).' },
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    emoji: '🗡️',
    tagline: 'Precise. Elusive. Deadly when unseen.',
    description: 'Rogues rely on skill, stealth, and their enemies\' vulnerabilities to get the upper hand. They are masters of a hit-and-run style of combat, striking with lethal precision when the moment is right.',
    hitDie: 8,
    primaryStat: 'DEX',
    armorProficiencies: ['Light'],
    weaponProficiencies: ['Simple', 'Hand crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    savingThrows: ['DEX', 'INT'],
    skillChoices: { count: 4, options: ['Acrobatics', 'Athletics', 'Deception', 'Insight', 'Intimidation', 'Investigation', 'Perception', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth'] },
    startingEquipment: ['Rapier', 'Shortbow', '20 arrows', 'Leather armor', "Thieves' tools", "Burglar's pack"],
    level1Abilities: [
      { name: 'Expertise', description: 'Choose 2 skills you are proficient in. Your proficiency bonus is doubled for those skills.' },
      { name: 'Sneak Attack', description: 'Once per turn, deal extra 1d6 damage when you have advantage or an ally is adjacent to your target.' },
      { name: "Thieves' Cant", description: 'You know a secret mix of language and signals used by the criminal underground.' },
    ],
  },
  {
    id: 'cleric',
    name: 'Cleric',
    emoji: '✨',
    tagline: 'Divine conduit. Healer. Unstoppable crusader.',
    description: 'Clerics are intermediaries between the mortal world and the divine. Wielding sacred power granted by their deity, they are fearsome warriors and life-saving healers — sometimes in the same breath.',
    hitDie: 8,
    primaryStat: 'WIS',
    armorProficiencies: ['Light', 'Medium', 'Shields'],
    weaponProficiencies: ['Simple'],
    savingThrows: ['WIS', 'CHA'],
    skillChoices: { count: 2, options: ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'] },
    startingEquipment: ['Mace', 'Scale mail', 'Shield', 'Holy symbol', "Priest's pack"],
    level1Abilities: [
      { name: 'Spellcasting', description: 'You can cast cleric spells using WIS as your spellcasting ability. Spell save DC = 8 + proficiency + WIS modifier.' },
      { name: 'Divine Domain', description: 'Choose a domain at level 1: Life (healing focused) or Light (radiant damage focused). Grants domain spells and features.' },
    ],
  },
  {
    id: 'ranger',
    name: 'Ranger',
    emoji: '🏹',
    tagline: 'Tracker. Hunter. Guardian of the wild places.',
    description: 'Rangers are warriors of the wilderness — hunters, trackers, and scouts who combine martial skill with a deep knowledge of the natural world. In their favored terrain, they are nearly impossible to evade.',
    hitDie: 10,
    primaryStat: 'DEX',
    armorProficiencies: ['Light', 'Medium', 'Shields'],
    weaponProficiencies: ['Simple', 'Martial'],
    savingThrows: ['STR', 'DEX'],
    skillChoices: { count: 3, options: ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception', 'Stealth', 'Survival'] },
    startingEquipment: ['Longbow', '20 arrows', 'Shortsword', 'Leather armor', "Explorer's pack"],
    level1Abilities: [
      { name: 'Favored Enemy', description: 'Choose a type of enemy (beasts, undead, humanoids, etc.). Advantage on survival checks to track them and on intelligence checks to recall information about them.' },
      { name: 'Natural Explorer', description: 'Choose a favored terrain type. While traveling in that terrain, difficult terrain does not slow your group, you cannot get lost by nonmagical means, and you remain alert while foraging.' },
    ],
  },
  {
    id: 'paladin',
    name: 'Paladin',
    emoji: '🛡️',
    tagline: 'Oath-bound warrior. Holy avenger. Unbreakable.',
    description: 'Paladins are holy warriors who have sworn sacred oaths to uphold justice, protect the innocent, or destroy evil. They combine the toughness of a fighter with divine spellcasting and auras that shield their allies.',
    hitDie: 10,
    primaryStat: 'STR',
    armorProficiencies: ['Light', 'Medium', 'Heavy', 'Shields'],
    weaponProficiencies: ['Simple', 'Martial'],
    savingThrows: ['WIS', 'CHA'],
    skillChoices: { count: 2, options: ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'] },
    startingEquipment: ['Longsword', 'Shield', 'Chain mail', 'Holy symbol', "Priest's pack"],
    level1Abilities: [
      { name: 'Divine Sense', description: 'As an action, detect the presence of powerful good or evil within 60 ft. Usable 1 + CHA modifier times per long rest.' },
      { name: 'Lay on Hands', description: 'A pool of healing power equal to 5 × paladin level. As an action, restore HP from this pool to a creature you touch.' },
    ],
  },
];

export const getClassById = (id) => CLASSES.find(c => c.id === id);
