export const RACES = [
  {
    id: 'human',
    name: 'Human',
    emoji: '⚔️',
    tagline: 'Adaptable. Ambitious. Everywhere.',
    lore: 'Humans are the most widespread people in the known world — short-lived but fiercely determined. Their adaptability has built empires and toppled them in equal measure.',
    statBonuses: { STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1 },
    traits: [
      { name: 'Versatile', description: 'Gain +1 to all ability scores.' },
      { name: 'Extra Language', description: 'You speak one additional language of your choice.' },
    ],
    speed: 30,
    size: 'Medium',
  },
  {
    id: 'elf',
    name: 'Elf',
    emoji: '🌿',
    tagline: 'Ancient. Perceptive. Unbowed by time.',
    lore: 'Elves have walked the world since before the first cities rose from the mud. They see centuries where others see years, and carry the weight of memory like armor.',
    statBonuses: { DEX: 2, INT: 1 },
    traits: [
      { name: 'Keen Senses', description: 'Proficiency in the Perception skill.' },
      { name: 'Fey Ancestry', description: 'Advantage on saving throws against being charmed. Magic cannot put you to sleep.' },
      { name: 'Trance', description: 'You do not sleep. Instead you meditate for 4 hours, gaining the benefits of a long rest.' },
    ],
    speed: 30,
    size: 'Medium',
  },
  {
    id: 'dwarf',
    name: 'Dwarf',
    emoji: '🪨',
    tagline: 'Stubborn. Enduring. Carved from mountain stone.',
    lore: 'Dwarves are a people of stone and forge. Their clans remember every slight and every debt across generations — and they settle both with equal thoroughness.',
    statBonuses: { CON: 2, WIS: 1 },
    traits: [
      { name: 'Darkvision', description: 'See in dim light as if bright, in darkness as if dim, up to 60 ft.' },
      { name: 'Dwarven Resilience', description: 'Advantage on saving throws against poison. Resistance to poison damage.' },
      { name: 'Stonecunning', description: 'Double proficiency bonus on History checks related to stonework.' },
    ],
    speed: 25,
    size: 'Medium',
  },
  {
    id: 'halfling',
    name: 'Halfling',
    emoji: '🍀',
    tagline: 'Lucky. Quiet-footed. Impossible to rattle.',
    lore: 'Halflings slide through the world like water through stone — unobtrusive, resourceful, and possessed of an uncanny fortune that larger folk can only envy.',
    statBonuses: { DEX: 2, CHA: 1 },
    traits: [
      { name: 'Lucky', description: 'When you roll a 1 on an attack roll, ability check, or saving throw, reroll and use the new result.' },
      { name: 'Brave', description: 'Advantage on saving throws against being frightened.' },
      { name: 'Halfling Nimbleness', description: 'You can move through the space of any creature larger than you.' },
    ],
    speed: 25,
    size: 'Small',
  },
  {
    id: 'half-elf',
    name: 'Half-Elf',
    emoji: '🌗',
    tagline: 'Between worlds. At home in neither. Stronger for it.',
    lore: 'Born of two worlds, half-elves carry the charm of their elven heritage and the drive of their human blood. They are diplomats by necessity and survivors by nature.',
    statBonuses: { CHA: 2, DEX: 1, INT: 1 },
    traits: [
      { name: 'Fey Ancestry', description: 'Advantage on saving throws against being charmed. Magic cannot put you to sleep.' },
      { name: 'Skill Versatility', description: 'Gain proficiency in two skills of your choice.' },
    ],
    speed: 30,
    size: 'Medium',
  },
  {
    id: 'orc',
    name: 'Orc',
    emoji: '💀',
    tagline: 'Ferocious. Relentless. Harder to kill than most.',
    lore: 'Orcs have been called monsters by those who fear them and legends by those who have fought alongside them. They are a people of war — but war is not all they are.',
    statBonuses: { STR: 2, CON: 1 },
    traits: [
      { name: 'Relentless Endurance', description: 'When reduced to 0 HP but not killed, drop to 1 HP instead. Once per long rest.' },
      { name: 'Savage Attacks', description: 'On a critical hit with a melee weapon, roll one extra damage die.' },
      { name: 'Darkvision', description: 'See in dim light as if bright, in darkness as if dim, up to 60 ft.' },
    ],
    speed: 30,
    size: 'Medium',
  },
];

export const getRaceById = (id) => RACES.find(r => r.id === id);
