// ─── Aranthos World Bible — Static Constants ─────────────────────────────────
// World: Araxys  |  Kingdom: Aranthos
// This file is reference data only. Never mutate these objects at runtime.
// Dynamic player state (faction rep, NPC dispositions, visited locations)
// lives in GameContext and is persisted via storage.js.

export const WORLD_NAME = 'Araxys';
export const KINGDOM_NAME = 'Aranthos';

// ─── Regions ─────────────────────────────────────────────────────────────────

export const REGIONS = [
  {
    id: 'heartlands',
    name: 'The Heartlands',
    dominant_race: 'human',
    faction_control: 'crown',
    tone: 'stable_anxious',
    description: 'Fertile plains and rolling hills. The seat of the Crown. Agricultural wealth — grain, livestock, wool. Most major roads converge here. Stable on the surface, but Crown patrols have doubled and nobody is talking about why.',
  },
  {
    id: 'thornwood',
    name: 'The Thornwood',
    dominant_race: 'elf',
    faction_control: 'thornbound',
    tone: 'mysterious_beautiful',
    description: 'An ancient forest, centuries old, so dense in places the sun never reaches the floor. Elven settlements are woven into the canopy — you don\'t find them, they find you. Fey creatures roam at dusk. Beautiful, strange, and profoundly unwelcoming to those who don\'t respect it.',
  },
  {
    id: 'ashpeaks',
    name: 'The Ashpeaks',
    dominant_race: 'dwarf',
    faction_control: 'deep_accord',
    tone: 'industrial_proud',
    description: 'A rugged mountain range with dwarven holds carved deep into the rock. Rich ore veins. Massive forges that never go dark. Cold, industrious, and proud. The Deep Accord was born here and controls almost everything that moves through these mountains.',
  },
  {
    id: 'lowfen',
    name: 'The Lowfen',
    dominant_race: 'halfling',
    faction_control: 'none',
    tone: 'friendly_hidden_depths',
    description: 'Marshlands and river deltas cut through by a thousand waterways. Halflings and gnomes thrive here, navigating by barge and raised wooden road. Foggy mornings, humid summers. The best herbalists and alchemists in the kingdom operate out of the Lowfen.',
  },
  {
    id: 'scorched_reach',
    name: 'The Scorched Reach',
    dominant_race: 'orc',
    faction_control: 'broken_chain',
    tone: 'harsh_proud',
    description: 'Arid steppes and badlands baking under a harsh sun. Orc and half-orc clans live as they have for centuries — nomadic, fierce, deeply misunderstood by the western regions. The Broken Chain movement has its roots here, born from generations of land theft and discrimination by Crown settlers.',
  },
  {
    id: 'tidebreak_coast',
    name: 'The Tidebreak Coast',
    dominant_race: 'mixed',
    faction_control: 'crimson_veil_shadow',
    tone: 'cosmopolitan_flexible',
    description: 'Coastal cliffs, hidden coves, and harbor towns where all races meet and trade. The most cosmopolitan region in Aranthos. Merchant wealth and piracy coexist openly. The Crimson Veil\'s shadow network is strongest here.',
  },
  {
    id: 'emberveil',
    name: 'The Emberveil',
    dominant_race: 'emberkin',
    faction_control: 'ashen_circle',
    tone: 'insular_powerful',
    description: 'Volcanic plateaus and obsidian plains above geothermal vents. Emberkin and Scaledborn have held this territory for generations — feared and misunderstood by the rest of the kingdom. Their forges are powered by the earth itself. The Ashen Circle has deep roots here.',
  },
];

// ─── Locations ────────────────────────────────────────────────────────────────

export const LOCATIONS = [
  // ── Capital ──
  {
    id: 'aldenmere',
    name: 'Aldenmere',
    type: 'capital',
    region: 'heartlands',
    population: 50000,
    visited: false,
    spawn_point: true,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'temple_solmaren', 'temple_vrethis_hidden', 'royal_audience'],
    faction_presence: ['crown', 'crimson_veil', 'ashen_circle', 'deep_accord'],
    notes: 'The crown jewel of Aranthos. Spans both banks of the Greyveil River. The Crown Palace dominates the northern hill. The Undercity catacombs run for miles beneath. Spawn point: The Whetted Compass inn.',
  },
  // ── Large Cities ──
  {
    id: 'crestmere',
    name: 'Crestmere',
    type: 'large_city',
    region: 'tidebreak_coast',
    population: 20000,
    visited: false,
    spawn_point: true,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'harbor', 'merchants_exchange'],
    faction_presence: ['crimson_veil', 'deep_accord', 'broken_chain_minor'],
    notes: 'Primary port. Most cosmopolitan. The Sea Witch apothecary is here. Crimson Veil strongest presence.',
  },
  {
    id: 'ironhold',
    name: 'Ironhold',
    type: 'large_city',
    region: 'ashpeaks',
    population: 15000,
    visited: false,
    spawn_point: true,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'temple_durrak', 'deep_accord_guildhall'],
    faction_presence: ['deep_accord', 'crown_minor'],
    notes: 'Dwarven stronghold city. Deep Accord HQ. Forges never stop.',
  },
  {
    id: 'thornhaven',
    name: 'Thornhaven',
    type: 'large_city',
    region: 'thornwood',
    population: 12000,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'rangers_guildhall', 'thornwood_gate'],
    faction_presence: ['thornbound', 'crown_minor', 'rangers_guild'],
    notes: 'Human-elf border town. Uneasy coexistence. Thornwood Gate passage by elf permission only.',
  },
  {
    id: 'embervast',
    name: 'Embervast',
    type: 'large_city',
    region: 'emberveil',
    population: 10000,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'ashen_circle_chapter'],
    faction_presence: ['ashen_circle', 'crown_absent'],
    notes: 'Emberkin/Scaledborn city. Ashen Circle primary chapter house. Volcanic architecture.',
  },
  // ── Medium Cities ──
  {
    id: 'millford',
    name: 'Millford',
    type: 'medium_city',
    region: 'heartlands',
    population: 8000,
    visited: false,
    spawn_point: true,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'magistrate'],
    faction_presence: ['crown', 'iron_compact_encampment'],
    notes: 'Grain crossroads. Iron Compact encampment visible and threatening. Nervous energy throughout.',
  },
  {
    id: 'deepwell',
    name: 'Deepwell',
    type: 'medium_city',
    region: 'lowfen',
    population: 6000,
    visited: false,
    spawn_point: true,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'river_barge'],
    faction_presence: ['none_dominant'],
    notes: 'River trade hub. Halfling-majority. Best apothecaries. Fenhollow mystery nearby.',
  },
  {
    id: 'ashford',
    name: 'Ashford',
    type: 'medium_city',
    region: 'scorched_reach',
    population: 5000,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary'],
    faction_presence: ['crown_weak', 'broken_chain'],
    notes: 'Frontier settlement. Human-orc tension actively boiling.',
  },
  {
    id: 'saltwick',
    name: 'Saltwick',
    type: 'medium_city',
    region: 'tidebreak_coast',
    population: 4000,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith', 'merchant', 'apothecary', 'black_market'],
    faction_presence: ['crimson_veil'],
    notes: 'Smuggling port. Crimson Veil transit point. Corrupt magistrate.',
  },
  // ── Small Towns ──
  {
    id: 'dunharrow',
    name: 'Dunharrow',
    type: 'small_town',
    region: 'heartlands',
    population: 800,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith'],
    faction_presence: ['crown_minimal'],
    notes: 'Quiet farming village. Suspicious of strangers. Dying courier main plot hook. Greymere Ruins nearby.',
  },
  {
    id: 'grayveil',
    name: 'Grayveil',
    type: 'small_town',
    region: 'thornwood',
    population: 1200,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'blacksmith', 'merchant'],
    faction_presence: ['crown_weak', 'thornbound_covert'],
    notes: 'Logging town. Thornbound sabotage ongoing. Active tension with elves.',
  },
  {
    id: 'kettlerock',
    name: 'Kettlerock',
    type: 'small_town',
    region: 'ashpeaks',
    population: 1500,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'merchant'],
    faction_presence: ['deep_accord_minor'],
    notes: 'Mining supply town. Mostly humans serving dwarven operations.',
  },
  {
    id: 'cinder_cross',
    name: 'Cinder Cross',
    type: 'small_town',
    region: 'scorched_reach',
    population: 600,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'merchant'],
    faction_presence: ['broken_chain_open'],
    notes: 'Half-orc majority. Broken Chain organizing openly. Krag Ironvoice visits regularly.',
  },
  {
    id: 'mossbridge',
    name: 'Mossbridge',
    type: 'small_town',
    region: 'lowfen',
    population: 900,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'merchant'],
    faction_presence: ['none'],
    notes: 'Gnome bridge engineers. Strange local festivals. Fen Road maintenance hub.',
  },
  {
    id: 'coppervane',
    name: 'Coppervane',
    type: 'small_town',
    region: 'tidebreak_coast',
    population: 700,
    visited: false,
    spawn_point: false,
    available_services: ['inn', 'merchant'],
    faction_presence: ['none'],
    notes: 'Small fishing village. Peaceful. Occasional pirate visits.',
  },
  // ── Camps & Waypoints ──
  {
    id: 'waystone_rest',
    name: 'The Waystone Rest',
    type: 'camp',
    region: 'heartlands',
    population: 0,
    visited: false,
    spawn_point: true,
    available_services: ['campfire', 'occasional_merchant'],
    faction_presence: ['varies'],
    notes: "King's Road junction camp. Random travelers pass through. Good for open-world intro.",
  },
  {
    id: 'hunters_rest',
    name: "Hunter's Rest",
    type: 'camp',
    region: 'thornwood',
    population: 0,
    visited: false,
    spawn_point: true,
    available_services: ['shelter', 'smokehouse'],
    faction_presence: ['rangers'],
    notes: 'Thornwood edge camp. Good for atmospheric forest start.',
  },
  {
    id: 'black_moor_camp',
    name: 'The Black Moor Camp',
    type: 'camp',
    region: 'scorched_reach',
    population: 0,
    visited: false,
    spawn_point: true,
    available_services: ['campfire', 'orc_traders'],
    faction_presence: ['broken_chain_adjacent'],
    notes: 'Orc clan seasonal ground. Outsiders tolerated if respectful. Unique perspective start.',
  },
  {
    id: 'embers_end',
    name: "Ember's End",
    type: 'camp',
    region: 'emberveil',
    population: 0,
    visited: false,
    spawn_point: true,
    available_services: ['campfire', 'tiefling_traders_occasional'],
    faction_presence: ['none'],
    notes: 'Volcanic rock outcropping. Emberkin traders pass through. Eerie atmosphere.',
  },
];

// ─── Ruins & Dungeons ─────────────────────────────────────────────────────────

export const RUINS = [
  {
    id: 'sunken_vaults',
    name: 'The Sunken Vaults',
    location: 'aldenmere_beneath',
    status: 'partially_sealed',
    connected_factions: ['ashen_circle', 'crimson_veil'],
    connected_deity: 'the_unnamed',
    danger_level: 4,
    discovered: false,
    notes: 'Ancient pre-kingdom catacombs running beneath Aldenmere. Something was sealed here before Aranthos existed. The Ashen Circle petitions for access. The Crown refuses. Connected to the main plot.',
  },
  {
    id: 'greymere_ruins',
    name: 'Greymere Ruins',
    location: 'heartlands_near_dunharrow',
    status: 'occupied_by_bandits',
    connected_factions: [],
    connected_deity: null,
    danger_level: 2,
    discovered: false,
    notes: 'A fortress that fell two hundred years ago. Bandits in the outer walls. They do not go below the basement level — and neither would you if you\'d seen what they\'d seen.',
  },
  {
    id: 'thornspire',
    name: 'The Thornspire',
    location: 'thornwood_interior',
    status: 'corrupted',
    connected_factions: ['thornbound_avoidance'],
    connected_deity: 'the_unnamed',
    danger_level: 4,
    discovered: false,
    notes: 'Ancient elven watchtower from before the kingdom existed. The Thornbound will not discuss it. Strange lights at night. Even the fey give it wide berth. Something changed inside within the last decade.',
  },
  {
    id: 'deepstone_halls',
    name: 'Deepstone Halls',
    location: 'ashpeaks',
    status: 'sealed',
    connected_factions: ['deep_accord_wants_open', 'dwarven_elders_forbid'],
    connected_deity: null,
    danger_level: 5,
    discovered: false,
    notes: 'A dwarven mine sealed three generations ago. Richest ore vein in the Ashpeaks. Deep Accord wants it reopened. Every dwarven elder has forbidden it. The debate is tearing the Deep Accord apart.',
  },
  {
    id: 'ashen_citadel',
    name: 'The Ashen Citadel',
    location: 'emberveil_volcanic_plateau',
    status: 'active_stirring',
    connected_factions: ['ashen_circle', 'scaledborn_ancestral'],
    connected_deity: 'the_unnamed',
    danger_level: 5,
    discovered: false,
    notes: 'Pre-civilisation ruin atop an active volcanic plateau. Scaledborn consider it ancestral holy ground. Something stirs inside when the volcano is active. The Ashen Circle believes this site and the Sunken Vaults are connected.',
  },
  {
    id: 'fenhollow',
    name: 'The Fenhollow',
    location: 'lowfen_submerged',
    status: 'submerged_active',
    connected_factions: [],
    connected_deity: 'unknown',
    danger_level: 3,
    discovered: false,
    notes: 'A structure barely visible above the swamp water. Halfling fishermen have reported rhythmic chanting from below for generations. Three expeditions went in. Two came back, and neither would speak about what they found.',
  },
];

// ─── Factions ─────────────────────────────────────────────────────────────────

export const FACTIONS = {
  crown: {
    id: 'crown',
    name: 'The Crown of Aranthos',
    leader: 'King Aldric III',
    actual_power: 'Lord Chancellor Maren Voss',
    symbol: 'Gold crown on white field',
    goal: 'Maintain stability and control the succession. Voss has a specific candidate in mind.',
    tension_level: 45,
    public_knowledge: true,
    color: 'gold_white',
    notes: 'The last legitimate authority in Aranthos, currently running on inertia. King Aldric III is secretly dying. His Chancellor makes the real decisions.',
  },
  iron_compact: {
    id: 'iron_compact',
    name: 'The Iron Compact',
    leader: 'General Sera Valdun',
    symbol: 'Iron-grey banner, clenched fist',
    goal: 'Military transition of power. A strong hand, not a dying king.',
    tension_level: 68,
    public_knowledge: true,
    color: 'iron_grey_red',
    notes: 'A coalition of generals and war captains building a private army. Not subtle about it. Can be an ally if the player seems capable.',
  },
  thornbound: {
    id: 'thornbound',
    name: 'The Thornbound Conclave',
    leader: 'Elder Vaelith of the Silver Root',
    symbol: 'Green and silver, leaf-woven banner',
    goal: 'Full legal independence for the Thornwood.',
    tension_level: 55,
    public_knowledge: true,
    color: 'green_silver',
    notes: 'Centuries of encroachment have radicalised a portion of the elven population. Elder Vaelith insists on restraint. Younger members are losing patience.',
  },
  deep_accord: {
    id: 'deep_accord',
    name: 'The Deep Accord',
    leader: 'Guildmaster Thora Coppervault',
    symbol: 'Bronze scales on brown field',
    goal: 'Economic autonomy and the best available deal.',
    tension_level: 30,
    public_knowledge: true,
    color: 'bronze_brown',
    notes: 'Controls the majority of Aranthos\'s metal production. Currently funding three different factions simultaneously while waiting to see who wins. Everything is a transaction.',
  },
  crimson_veil: {
    id: 'crimson_veil',
    name: 'The Crimson Veil',
    leader: 'The Weaver (identity unknown)',
    symbol: 'Crimson coin with veil motif',
    goal: 'Profit from instability. Maintain leverage over every faction.',
    tension_level: 0,
    public_knowledge: false,
    color: 'crimson_black',
    notes: 'Sells secrets to all sides. Agents look like seamstresses, merchants, dock workers, and inn staff. They do not want to rule — they want to remain indispensable.',
  },
  ashen_circle: {
    id: 'ashen_circle',
    name: 'The Ashen Circle',
    leader: 'Archmagus Delvryn Osk',
    symbol: 'Purple and grey, serpent eating its tail',
    goal: 'Political recognition for mages. Solve the king\'s poisoning. Understand The Unnamed.',
    tension_level: 42,
    public_knowledge: false,
    color: 'purple_grey',
    notes: 'Magic practitioners exist in a legal grey zone. Osk believes the king\'s poison is magical in origin. Solving it would give them the leverage they\'ve always sought.',
  },
  broken_chain: {
    id: 'broken_chain',
    name: 'The Broken Chain',
    leader: 'Krag Ironvoice',
    symbol: 'Orange broken chain on black field',
    goal: 'Land rights, equal legal standing, end to discriminatory Crown policy.',
    tension_level: 72,
    public_knowledge: true,
    color: 'orange_black',
    notes: 'Three generations of land confiscation and casual brutality. Critical internal split between Krag\'s peaceful reform faction and a younger, angrier group that believes the kingdom will never give what must be taken.',
  },
};

// ─── Deities ──────────────────────────────────────────────────────────────────

export const DEITIES = [
  {
    id: 'solmaren',
    name: 'Solmaren, the Undying Flame',
    domains: ['light', 'justice', 'healing', 'order'],
    symbol: 'Sun with an open eye',
    worshippers: ['humans', 'crown_loyalists', 'paladins', 'clerics'],
    political_role: 'Crown uses Solmaren imagery to legitimise royal authority.',
    public: true,
    notes: 'Most widely worshipped deity in Aranthos. Clergy serve as healers, judges, and diplomats. High Priest Eddan in Aldenmere is the most politically powerful cleric in the kingdom.',
  },
  {
    id: 'vrethis',
    name: 'Vrethis, the Moonweaver',
    domains: ['shadow', 'secrets', 'fate', 'cycles'],
    symbol: 'Crescent moon with three silver threads',
    worshippers: ['rogues', 'emberkin', 'seers', 'travelers'],
    political_role: 'None official. Temples hidden.',
    public: true,
    notes: 'Not evil — misunderstood. Governs the spaces between: light and dark, choice and fate. Worship is private. Temple beneath Aldenmere\'s Scholars\' Quarter accessible by invitation only.',
  },
  {
    id: 'durrak',
    name: 'Durrak, the Undying Stone',
    domains: ['earth', 'forge', 'ancestors', 'endurance'],
    symbol: 'Hammer striking anvil over mountain peaks',
    worshippers: ['dwarves', 'smiths', 'fighters', 'miners'],
    political_role: 'Deep Accord cultural anchor. Ancestor veneration central to dwarven identity.',
    public: true,
    notes: 'Worshipped across races by anyone who works with stone or metal. Ancestor veneration is core — great deeds bring honour to the bloodline.',
  },
  {
    id: 'sylvara',
    name: 'Sylvara of the Turning Seasons',
    domains: ['nature', 'growth', 'death', 'rebirth'],
    symbol: 'A tree whose roots and branches form a perfect circle',
    worshippers: ['elves', 'druids', 'halflings', 'rangers', 'farmers'],
    political_role: 'Thornbound Conclave draws on Sylvara worship for their identity and justification.',
    public: true,
    notes: 'No permanent temples — worship happens outdoors, in groves and riverbanks. The Grove of Turning in the Thornwood is the holiest site.',
  },
  {
    id: 'the_unnamed',
    name: 'The Unnamed',
    domains: ['entropy', 'madness', 'void'],
    symbol: 'Circle with a slash — used as a warning, not a holy mark',
    worshippers: ['secret_cultists', 'desperate_mages'],
    political_role: 'Forbidden. Connected to the main plot. The Ashen Circle believes The Unnamed is linked to the king\'s poison.',
    public: false,
    notes: 'Worship is forbidden throughout Aranthos. Connected to the Sunken Vaults, the Thornspire, and the Ashen Citadel.',
  },
];

// ─── NPC Templates ────────────────────────────────────────────────────────────
// Static reference data. Never mutate at runtime.
// Dynamic disposition deltas live in GameContext.npcDispositions keyed by npc id.

export const NPC_TEMPLATES = [
  // ── Faction Leaders ──
  {
    id: 'king_aldric_iii',
    name: 'King Aldric III',
    role: 'King of Aranthos',
    race: 'human',
    age: 72,
    faction_affiliation: 'crown',
    deity: 'solmaren',
    location: 'aldenmere',
    disposition_default: 0,
    personality_tags: ['kind', 'tired', 'afraid', 'principled', 'uninformed_about_poison'],
    knowledge_tags: ['aranthos_history', 'crown_politics', 'succession_anxiety'],
    accessible: false,
    access_requirement: 'high_crown_reputation_or_main_plot_thread',
    reaction_modifiers: { crown: 20, solmaren_devout: 15, helped_citizens: 10 },
  },
  {
    id: 'lord_chancellor_voss',
    name: 'Lord Chancellor Maren Voss',
    role: 'Chancellor of Aranthos',
    race: 'human',
    age: 64,
    faction_affiliation: 'crown',
    deity: 'solmaren',
    location: 'aldenmere',
    disposition_default: -5,
    personality_tags: ['calculating', 'controlled', 'intelligent', 'genuinely_believes_himself_righteous', 'concealing_guilt'],
    knowledge_tags: ['kings_poison', 'succession_plan', 'all_faction_intelligence', 'aldenmere_politics'],
    accessible: true,
    is_main_plot_key: true,
    reaction_modifiers: { crown: 20, investigating_king_illness: -30, crimson_veil_contact: -15, iron_compact_ally: -20 },
  },
  {
    id: 'general_valdun',
    name: 'General Sera Valdun',
    role: 'Leader, The Iron Compact',
    race: 'human',
    age: 44,
    faction_affiliation: 'iron_compact',
    deity: 'solmaren',
    location: 'millford_camp',
    disposition_default: -10,
    personality_tags: ['decisive', 'magnetic', 'ruthless', 'certain', 'strategic'],
    knowledge_tags: ['iron_compact_plans', 'military_movements', 'king_instability_suspected'],
    accessible: true,
    reaction_modifiers: { soldier_class: 20, mage_class: -15, combat_reputation: 25, crown_ally: -30 },
  },
  {
    id: 'elder_vaelith',
    name: 'Elder Vaelith of the Silver Root',
    role: 'Leader, The Thornbound Conclave',
    race: 'elf',
    age: -1,
    faction_affiliation: 'thornbound',
    deity: 'sylvara',
    location: 'thornwood_deep',
    disposition_default: -20,
    personality_tags: ['ancient', 'patient', 'cryptic', 'principled', 'immovable'],
    knowledge_tags: ['thornwood_history', 'pre_kingdom_lore', 'thornspire_secret', 'elven_independence'],
    accessible: false,
    access_requirement: 'thornbound_trust_50_or_thornhaven_introduction',
    reaction_modifiers: { elf: 15, druid_ranger: 10, respects_thornwood: 20, logger_or_crown: -40, lied_to_thornbound: -60 },
  },
  {
    id: 'thora_coppervault',
    name: 'Guildmaster Thora Coppervault',
    role: 'Leader, The Deep Accord',
    race: 'dwarf',
    age: 180,
    faction_affiliation: 'deep_accord',
    deity: 'durrak',
    location: 'ironhold',
    disposition_default: 0,
    personality_tags: ['transactional', 'brilliant', 'pragmatic', 'laughs_easily', 'misses_nothing'],
    knowledge_tags: ['deep_accord_finances', 'ironhold_trade', 'all_faction_economic_ties', 'deepstone_halls_debate'],
    accessible: true,
    reaction_modifiers: { dwarf: 10, coin_or_goods: 15, honors_contracts: 25, impulsive_or_wasteful: -20 },
  },
  {
    id: 'archmagus_osk',
    name: 'Archmagus Delvryn Osk',
    role: 'Leader, The Ashen Circle',
    race: 'elf',
    age: -1,
    faction_affiliation: 'ashen_circle',
    deity: null,
    location: 'embervast',
    disposition_default: -5,
    personality_tags: ['obsessive', 'brilliant', 'unstable_under_surface', 'cryptic', 'goal_driven'],
    knowledge_tags: ['kings_poison_magical_theory', 'sunken_vaults', 'the_unnamed', 'ashen_citadel', 'thornspire_corruption'],
    accessible: true,
    is_main_plot_key: true,
    reaction_modifiers: { mage_class: 20, ruins_information: 30, unnamed_artifact: 40, crown_loyalist: -15 },
  },
  {
    id: 'krag_ironvoice',
    name: 'Krag Ironvoice',
    role: 'Leader, The Broken Chain',
    race: 'half_orc',
    age: 34,
    faction_affiliation: 'broken_chain',
    deity: null,
    location: 'cinder_cross',
    disposition_default: -15,
    personality_tags: ['passionate', 'intelligent', 'sincere', 'internally_conflicted', 'powerful_speaker'],
    knowledge_tags: ['broken_chain_movement', 'orc_clan_politics', 'scorched_reach_grievances', 'ashford_tensions'],
    accessible: true,
    reaction_modifiers: { orc_half_orc: 25, treats_orcs_respectfully: 20, helped_broken_chain: 30, crown_soldier: -40, magic_prominent: -10 },
  },
  // ── Key Story NPCs ──
  {
    id: 'sienna_drake',
    name: 'Sienna Drake',
    role: 'Royal Investigator',
    race: 'human',
    age: 32,
    faction_affiliation: 'crown',
    deity: 'vrethis',
    location: 'aldenmere',
    disposition_default: 5,
    personality_tags: ['sharp', 'cynical', 'determined', 'wry_humor', 'secretly_idealistic'],
    knowledge_tags: ['kings_illness_partial', 'crimson_veil_history', 'aldenmere_undercity', 'investigator_network'],
    accessible: true,
    is_main_plot_key: true,
    moves_with_plot: true,
    reaction_modifiers: { investigated_king_illness: 30, crimson_veil_history: 10, honest: 15, crown_loyalist_blind: -10 },
  },
  {
    id: 'corvin_ash',
    name: 'Corvin Ash',
    role: 'Traveling Bard (Wildcard)',
    race: 'human',
    age: -1,
    faction_affiliation: 'unknown',
    deity: 'vrethis_suspected',
    location: 'any_tavern',
    disposition_default: 20,
    personality_tags: ['charming', 'evasive', 'funny', 'knows_too_much', 'never_fully_honest'],
    knowledge_tags: ['all_city_rumors', 'faction_surface_intel', 'main_plot_hints', 'hidden_identity'],
    accessible: true,
    appears_in: ['aldenmere', 'crestmere', 'millford', 'ironhold', 'thornhaven', 'deepwell'],
    reaction_modifiers: { asks_smart_questions: 15, tips_generously: 10, interesting_reputation: 20, presses_about_identity: -5 },
  },
  // ── Location Innkeepers & Merchants ──
  {
    id: 'petra_amholt',
    name: 'Petra Amholt',
    role: 'Innkeeper, Aldenmere (The Whetted Compass)',
    race: 'human',
    age: 52,
    faction_affiliation: null,
    deity: 'solmaren',
    location: 'aldenmere',
    disposition_default: 10,
    personality_tags: ['observant', 'cautious', 'loyal', 'rumor_aware', 'protective_of_regulars'],
    knowledge_tags: ['aldenmere_rumors', 'crown_politics_surface', 'undercity_whispers'],
    accessible: true,
    reaction_modifiers: { crown_ally: 15, crimson_veil_known: -25, helped_locals: 20, crime_in_aldenmere: -40 },
  },
  {
    id: 'old_margret',
    name: 'Old Margret',
    role: 'Innkeeper, Crestmere (The Silver Anchor)',
    race: 'gnome',
    age: 95,
    faction_affiliation: null,
    deity: 'vrethis',
    location: 'crestmere',
    disposition_default: 15,
    personality_tags: ['gossipy', 'sharp', 'warm', 'excellent_memory', 'useful'],
    knowledge_tags: ['crestmere_rumors', 'harbor_comings_goings', 'merchant_exchange_gossip'],
    accessible: true,
    reaction_modifiers: { curious_asks_questions: 20, shares_rumors_in_return: 25, boring_or_closed: -10 },
  },
  {
    id: 'the_sea_witch',
    name: 'The Sea Witch',
    role: 'Apothecary, Crestmere',
    race: 'emberkin',
    age: -1,
    faction_affiliation: null,
    deity: 'vrethis',
    location: 'crestmere',
    disposition_default: -5,
    personality_tags: ['eccentric', 'knowledgeable', 'transactional', 'amoral_not_evil', 'perceptive'],
    knowledge_tags: ['rare_poisons', 'kings_poison_recognition', 'tidebreak_herbalism', 'vrethis_rites'],
    accessible: true,
    is_main_plot_key: true,
    reaction_modifiers: { emberkin: 15, worships_vrethis: 20, coin_or_favor: 25, crown_inquisitor: -50 },
  },
  {
    id: 'borin_copperkettle',
    name: 'Borin Copperkettle',
    role: 'Innkeeper, Ironhold (The Stone Cup)',
    race: 'dwarf',
    age: 210,
    faction_affiliation: 'deep_accord',
    deity: 'durrak',
    location: 'ironhold',
    disposition_default: 15,
    personality_tags: ['proud_host', 'competitive', 'warm', 'loyal_to_dwarves', 'loves_a_story'],
    knowledge_tags: ['ironhold_rumors', 'deep_accord_surface', 'ashpeaks_mining'],
    accessible: true,
    reaction_modifiers: { dwarf: 20, arm_wrestles_him: 15, respects_dwarven_customs: 15, disrespects_stone_cup: -30 },
  },
  {
    id: 'tilley_brightfoot',
    name: 'Tilley Brightfoot',
    role: 'Innkeeper, Thornhaven',
    race: 'halfling',
    age: 48,
    faction_affiliation: null,
    deity: 'sylvara',
    location: 'thornhaven',
    disposition_default: 20,
    personality_tags: ['cheerful', 'curious', 'asks_too_many_questions', 'excellent_host', 'harmlessly_nosy'],
    knowledge_tags: ['thornhaven_rumors', 'elven_quarter_news', 'rangers_guildhall_gossip'],
    accessible: true,
    reaction_modifiers: { answers_questions_warmly: 20, halfling_or_gnome: 10, rude_or_dismissive: -25 },
  },
  {
    id: 'razik',
    name: 'Razik',
    role: 'Innkeeper, Embervast',
    race: 'scaledborn',
    age: 55,
    faction_affiliation: null,
    deity: 'durrak',
    location: 'embervast',
    disposition_default: -10,
    personality_tags: ['formal', 'honorable', 'protective_of_guests', 'intimidating', 'deeply_hospitable_once_trusted'],
    knowledge_tags: ['embervast_rumors', 'ashen_circle_surface', 'scaledborn_culture', 'ashen_citadel_lore'],
    accessible: true,
    reaction_modifiers: { scaledborn_or_emberkin: 20, shows_respect_immediately: 25, dismissive_of_emberveil: -40 },
  },
  {
    id: 'pip_tannerfoot',
    name: 'Pip Tannerfoot',
    role: 'Innkeeper, Deepwell (The Muddy Boot)',
    race: 'halfling',
    age: 62,
    faction_affiliation: null,
    deity: 'sylvara',
    location: 'deepwell',
    disposition_default: 25,
    personality_tags: ['warm', 'proud_of_cooking', 'river_network_connected', 'good_listener', 'underestimates_danger'],
    knowledge_tags: ['deepwell_rumors', 'lowfen_river_routes', 'fenhollow_local_legend'],
    accessible: true,
    reaction_modifiers: { praises_fish_stew: 20, halfling: 10, asks_about_fenhollow: 5, violent_in_muddy_boot: -60 },
  },
  {
    id: 'fat_hal',
    name: 'Fat Hal',
    role: 'Innkeeper, Millford (The Golden Grain)',
    race: 'human',
    age: 45,
    faction_affiliation: null,
    deity: 'solmaren',
    location: 'millford',
    disposition_default: 20,
    personality_tags: ['loud', 'cheerful', 'fond_of_everyone', 'secretly_worried', 'community_anchor'],
    knowledge_tags: ['millford_rumors', 'iron_compact_movements', 'king_road_traffic'],
    accessible: true,
    reaction_modifiers: { friendly: 15, buys_rounds: 25, iron_compact: -10, causes_trouble: -40 },
  },
  {
    id: 'brother_tomis',
    name: 'Brother Tomis',
    role: 'Apothecary/Healer, Aldenmere',
    race: 'human',
    age: 58,
    faction_affiliation: 'solmaren_clergy',
    deity: 'solmaren',
    location: 'aldenmere',
    disposition_default: 15,
    personality_tags: ['compassionate', 'principled', 'knows_the_undercity', 'quietly_suspicious_of_palace'],
    knowledge_tags: ['aldenmere_poor', 'royal_healers_frustrated', 'undercity_health'],
    accessible: true,
    is_main_plot_key: true,
    reaction_modifiers: { helps_the_poor: 30, solmaren_devout: 20, asks_about_unusual_illness: 10 },
  },
  {
    id: 'brenn_harbormaster',
    name: 'Brenn',
    role: 'Harbormaster, Crestmere',
    race: 'half_orc',
    age: 40,
    faction_affiliation: 'broken_chain_sympathizer',
    deity: null,
    location: 'crestmere',
    disposition_default: -5,
    personality_tags: ['controlled', 'watchful', 'protective', 'slow_to_trust', 'loyal_once_earned'],
    knowledge_tags: ['crestmere_harbor_traffic', 'smuggling_routes', 'broken_chain_crestmere'],
    accessible: true,
    reaction_modifiers: { orc_half_orc: 20, treats_dock_workers_well: 15, crown_official: -20, broken_chain: 30 },
  },
];

// ─── Main Plot — The Dying Crown ──────────────────────────────────────────────

export const MAIN_PLOT = {
  id: 'dying_crown',
  title: 'The Dying Crown',
  stages: ['hidden', 'stirring', 'fracturing', 'breaking', 'resolved'],
  initial_stage: 'hidden',
  king_months_remaining: 6,
  // NOTE: poisoner identity is protected — do not surface this in DM prompts
  // until the player has earned the reveal through a discovery thread.
  poisoner_npc_id: 'lord_chancellor_voss',
  cure_exists: true,
  threads_available: [
    {
      id: 'thread_courier',
      name: 'The Dying Courier',
      location: 'dunharrow_road',
      trigger: 'player_travels_near_dunharrow',
      description: 'A dying messenger near Dunharrow carries a partial letter referencing the king\'s condition.',
    },
    {
      id: 'thread_sea_witch',
      name: 'The Sea Witch Knows',
      location: 'crestmere',
      trigger: 'player_visits_apothecary_or_describes_symptoms',
      description: 'The tiefling apothecary in Crestmere recognises the king\'s symptoms. Knows a cure exists. Will not speak without a significant favour.',
    },
    {
      id: 'thread_sienna',
      name: "Sienna Drake's Offer",
      location: 'aldenmere',
      trigger: 'player_has_reputation_5_or_more_in_aldenmere',
      description: 'The Royal Investigator approaches the player with a sensitive job offer.',
    },
    {
      id: 'thread_ashen_circle',
      name: "The Ashen Circle's Investigation",
      location: 'embervast',
      trigger: 'player_visits_ashen_circle_chapter',
      description: 'Archmagus Osk is investigating the same poison from a magical angle. Will trade information.',
    },
    {
      id: 'thread_crimson_veil',
      name: 'The Truth Has a Price',
      location: 'crestmere_or_aldenmere',
      trigger: 'player_has_crimson_veil_contact_and_sufficient_coin_or_favor',
      description: 'The Crimson Veil can sell the full picture — the poison, the poisoner, the timeline — for an extraordinary price.',
    },
  ],
};
